
---

# Sauvegarde

Facile : fonction `ggsave`   
Dernier plot (ou paramètre `plot = ...`)

```{r save, eval=FALSE}
ggsave('myfile.pdf', width = 8, height = 5, units = 'cm')
ggsave('myfile.eps', width = 8, height = 5, units = 'cm')
ggsave('myfile.png', width = 8, height = 5, units = 'cm', dpi = 300)
```

--
class: slide-class-advanced

Cairo PDF (en cas de polices de caractères personnalisées) :

```{r, eval=FALSE}
ggsave('myfile.pdf', device = cairo_pdf)
```

---
class: slide-class-advanced small-code

# Composition d'éléments

Pour éviter de répéter des éléments chaque fois :   
- objet `ggplot` + objet `list`

```{r comb-list}
my_opts <- list(
  scale_x_log10(), 
  scale_color_discrete('Cylindres'),
  ggtitle('Mon titre', subtitle = 'Sous-titre')
)
```

--

```{r comb-plot, fig.height=3}
ggplot(mtcars, aes(x = mpg, y = wt, col = factor(cyl))) + 
         geom_point() +
         my_opts   #<<
```


---

# Annotations

Vous pouvez ajouter des annotations où vous voulez : 
- couche `annotate(geom = ...)`   
- géométrie à choix, unités du graphique
- pas de lien avec des variables !

```{r annotate-plot, fig.height=3}
ggplot(mtcars) + 
    geom_point(aes(x = mpg, y = wt)) +
    annotate('text', x = 29, y = 3, label = 'Du texte', size = 6) +
    annotate("rect", xmin = 21, xmax = 30, ymin = 2, ymax = 4,
      alpha = .2, fill = 'red')
```

